development:
  adapter: postgresql
  encoding: unicode
  database: sdp_development
  pool: 5
  username: e911miri
  password: 


test:
  adapter: postgresql
  encoding: unicode
  database: sdp_test
  pool: 5
  username: e911miri
  password: 
